version: '3.8'

services:
  akeneo:
    image: websoft9dev/akeneo:${APP_VERSION}
    container_name: ${APP_NAME}
    env_file: .env
    ports:
      - ${APP_HTTP_PORT}:80
    volumes:
      - akeneo:/var/www/html
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    restart: unless-stopped
    environment:
      AKENEO_MYSQL_DATABASE: ${APP_DB_MYSQL_NAME}
      AKENEO_MYSQL_USER: ${APP_DB_MYSQL_USER}
      AKENEO_MYSQL_PASSWORD: ${APP_DB_MYSQL_PASSWORD}
      AKENEO_MYSQL_HOST: $APP_NAME-db
      AKENEO_SITENAME: ${APP_SITENAME}
      AKENEO_ADMIN_USER: ${APP_ADMIN_NAME}
      AKENEO_ADMIN_PASSWORD: ${APP_ADMIN_PASSWORD}
      
  mysql:
    image: mysql:${APP_DB_MYSQL_VERSION}
    container_name: $APP_NAME-db
    restart: unless-stopped
    ports:
     - ${APP_DB_MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${APP_DB_MYSQL_NAME}
      MYSQL_USER: ${APP_DB_MYSQL_USER}
      MYSQL_PASSWORD: ${APP_DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${APP_DB_MYSQL_PASSWORD}

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:${APP_DB_ES_VERSION}'
    container_name: ${APP_NAME}-elasticsearch
    restart: unless-stopped
    environment:
      ES_JAVA_OPTS: '${ES_JAVA_OPTS:--Xms512m -Xmx512m}'
      discovery.type: 'single-node'
    ports:
      - '${APP_DB_ES_PORT}:9200'


networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  akeneo:
  mysql:
